name: GitOps K3s Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-k3s:
    runs-on: self-hosted # Roda na VM lx01
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Sincronizar e Aplicar Manifestos via SSH no K3s
        run: |
          echo "Enviando manifestos para o control-plane (k3s-node01)..."
          
          # Garante que o diretório existe e envia os arquivos via SCP
          ssh -o StrictHostKeyChecking=no root@192.168.0.10 "mkdir -p /opt/k8s-manifests"
          scp -o StrictHostKeyChecking=no -r apps/ root@192.168.0.10:/opt/k8s-manifests/
          
          echo "Aplicando alterações declarativas no cluster..."
          ssh -o StrictHostKeyChecking=no root@192.168.0.10 "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml && kubectl apply -R -f /opt/k8s-manifests/apps/"
          
          echo "Validando pods em execução no cluster..."
          ssh -o StrictHostKeyChecking=no root@192.168.0.10 "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml && kubectl get pods -o wide"

      - name: Testar Saúde da Aplicação
        run: |
          echo "Testando requisição HTTP interna..."
          curl -I http://192.168.0.10:30080
          
          echo "====================================================="
          echo "TUDO PRONTO! Acesse publicamente pelo seu domínio:"
          echo "http://app.bliciolab.com.br"
          echo "====================================================="